const SupportedCountryCodes = [
    { value: 'AF', label: 'Afghanistan (+93)', code: '+93' },
    { value: 'AL', label: 'Albania (+355)', code: '+355' },
    { value: 'DZ', label: 'Algeria (+213)', code: '+213' },
    { value: 'AS', label: 'American Samoa (+1-684)', code: '+1-684' },
    { value: 'AD', label: 'Andorra (+376)', code: '+376' },
    { value: 'AO', label: 'Angola (+244)', code: '+244' },
    { value: 'AI', label: 'Anguilla (+1-264)', code: '+1-264' },
    { value: 'AG', label: 'Antigua and Barbuda (+1-268)', code: '+1-268' },
    { value: 'AR', label: 'Argentina (+54)', code: '+54' },
    { value: 'AM', label: 'Armenia (+374)', code: '+374' },
    { value: 'AU', label: 'Australia (+61)', code: '+61' },
    { value: 'AT', label: 'Austria (+43)', code: '+43' },
    { value: 'AZ', label: 'Azerbaijan (+994)', code: '+994' },
    { value: 'BS', label: 'Bahamas (+1-242)', code: '+1-242' },
    { value: 'BH', label: 'Bahrain (+973)', code: '+973' },
    { value: 'BD', label: 'Bangladesh (+880)', code: '+880' },
    { value: 'BB', label: 'Barbados (+1-246)', code: '+1-246' },
    { value: 'BY', label: 'Belarus (+375)', code: '+375' },
    { value: 'BE', label: 'Belgium (+32)', code: '+32' },
    { value: 'BZ', label: 'Belize (+501)', code: '+501' },
    { value: 'BJ', label: 'Benin (+229)', code: '+229' },
    { value: 'BM', label: 'Bermuda (+1-441)', code: '+1-441' },
    { value: 'BT', label: 'Bhutan (+975)', code: '+975' },
    { value: 'BO', label: 'Bolivia (+591)', code: '+591' },
    { value: 'BA', label: 'Bosnia and Herzegovina (+387)', code: '+387' },
    { value: 'BW', label: 'Botswana (+267)', code: '+267' },
    { value: 'BR', label: 'Brazil (+55)', code: '+55' },
    { value: 'IO', label: 'British Indian Ocean Territory (+246)', code: '+246' },
    { value: 'VG', label: 'British Virgin Islands (+1-284)', code: '+1-284' },
    { value: 'BN', label: 'Brunei (+673)', code: '+673' },
    { value: 'BG', label: 'Bulgaria (+359)', code: '+359' },
    { value: 'BF', label: 'Burkina Faso (+226)', code: '+226' },
    { value: 'BI', label: 'Burundi (+257)', code: '+257' },
    { value: 'KH', label: 'Cambodia (+855)', code: '+855' },
    { value: 'CM', label: 'Cameroon (+237)', code: '+237' },
    { value: 'CA', label: 'Canada (+1)', code: '+1' },
    { value: 'CV', label: 'Cape Verde (+238)', code: '+238' },
    { value: 'KY', label: 'Cayman Islands (+1-345)', code: '+1-345' },
    { value: 'CF', label: 'Central African Republic (+236)', code: '+236' },
    { value: 'TD', label: 'Chad (+235)', code: '+235' },
    { value: 'CL', label: 'Chile (+56)', code: '+56' },
    { value: 'CN', label: 'China (+86)', code: '+86' },
    { value: 'CO', label: 'Colombia (+57)', code: '+57' },
    { value: 'KM', label: 'Comoros (+269)', code: '+269' },
    { value: 'CG', label: 'Congo (+242)', code: '+242' },
    { value: 'CD', label: 'Congo (DRC) (+243)', code: '+243' },
    { value: 'CR', label: 'Costa Rica (+506)', code: '+506' },
    { value: 'HR', label: 'Croatia (+385)', code: '+385' },
    { value: 'CU', label: 'Cuba (+53)', code: '+53' },
    { value: 'CY', label: 'Cyprus (+357)', code: '+357' },
    { value: 'CZ', label: 'Czech Republic (+420)', code: '+420' },
    { value: 'DK', label: 'Denmark (+45)', code: '+45' },
    { value: 'DJ', label: 'Djibouti (+253)', code: '+253' },
    { value: 'DM', label: 'Dominica (+1-767)', code: '+1-767' },
    { value: 'DO', label: 'Dominican Republic (+1-809, +1-829, +1-849)', code: '+1-809' },
    { value: 'EC', label: 'Ecuador (+593)', code: '+593' },
    { value: 'EG', label: 'Egypt (+20)', code: '+20' },
    { value: 'SV', label: 'El Salvador (+503)', code: '+503' },
    { value: 'GQ', label: 'Equatorial Guinea (+240)', code: '+240' },
    { value: 'ER', label: 'Eritrea (+291)', code: '+291' },
    { value: 'EE', label: 'Estonia (+372)', code: '+372' },
    { value: 'ET', label: 'Ethiopia (+251)', code: '+251' },
    { value: 'FJ', label: 'Fiji (+679)', code: '+679' },
    { value: 'FI', label: 'Finland (+358)', code: '+358' },
    { value: 'FR', label: 'France (+33)', code: '+33' },
    { value: 'GA', label: 'Gabon (+241)', code: '+241' },
    { value: 'GM', label: 'Gambia (+220)', code: '+220' },
    { value: 'GE', label: 'Georgia (+995)', code: '+995' },
    { value: 'DE', label: 'Germany (+49)', code: '+49' },
    { value: 'GH', label: 'Ghana (+233)', code: '+233' },
    { value: 'GI', label: 'Gibraltar (+350)', code: '+350' },
    { value: 'GR', label: 'Greece (+30)', code: '+30' },
    { value: 'GL', label: 'Greenland (+299)', code: '+299' },
    { value: 'GD', label: 'Grenada (+1-473)', code: '+1-473' },
    { value: 'GU', label: 'Guam (+1-671)', code: '+1-671' },
    { value: 'GT', label: 'Guatemala (+502)', code: '+502' },
    { value: 'GN', label: 'Guinea (+224)', code: '+224' },
    { value: 'GW', label: 'Guinea-Bissau (+245)', code: '+245' },
    { value: 'GY', label: 'Guyana (+592)', code: '+592' },
    { value: 'HT', label: 'Haiti (+509)', code: '+509' },
    { value: 'HN', label: 'Honduras (+504)', code: '+504' },
    { value: 'HK', label: 'Hong Kong (+852)', code: '+852' },
    { value: 'HU', label: 'Hungary (+36)', code: '+36' },
    { value: 'IS', label: 'Iceland (+354)', code: '+354' },
    { value: 'IN', label: 'India (+91)', code: '+91' },
    { value: 'ID', label: 'Indonesia (+62)', code: '+62' },
    { value: 'IR', label: 'Iran (+98)', code: '+98' },
    { value: 'IQ', label: 'Iraq (+964)', code: '+964' },
    { value: 'IE', label: 'Ireland (+353)', code: '+353' },
    { value: 'IL', label: 'Israel (+972)', code: '+972' },
    { value: 'IT', label: 'Italy (+39)', code: '+39' },
    { value: 'JM', label: 'Jamaica (+1-876)', code: '+1-876' },
    { value: 'JP', label: 'Japan (+81)', code: '+81' },
    { value: 'JO', label: 'Jordan (+962)', code: '+962' },
    { value: 'KZ', label: 'Kazakhstan (+7)', code: '+7' },
    { value: 'KE', label: 'Kenya (+254)', code: '+254' },
    { value: 'KI', label: 'Kiribati (+686)', code: '+686' },
    { value: 'KW', label: 'Kuwait (+965)', code: '+965' },
  ];
  
  export default SupportedCountryCodes;
  